export default {
  'Getting Started': "起手式",
  'Core Concepts': "核心概念",
  'Customization': "客製化",
  'Community': "社群",
  'Base Styles':"基底樣式",
  'Flexbox & Grid':'Flexbox & Grid',
  'Spacing':'Spacing',
  'Sizing':'Sizing',
  'Typography':'Typography',
  'Backgrounds':'Backgrounds',
  'Borders':'Borders',
  'Effects':'Effects',
  'Filters':'Filters',
  'Transitions & Animation':'Transitions & Animation',
  'Transforms':'Transforms',
  'Interactivity':'Interactivity',
  'SVG':'SVG',
  'Accessibility':'Accessibility',
  'Official Plugins':'Official Plugins',
}