name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click
  repository_dispatch:
    types: [sync-event]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ashramwen
          base: master
          head: master
